<?php 
/**
 * Magpedia_Storelocator extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Magpedia
 * @package	Magpedia_Storelocator
 * @copyright  	Copyright (c) 2014
 * @license http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Store list template
 *
 * @category	Magpedia
 * @package		Magpedia_Storelocator
 * @author Magpedia
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title storelocator-title">
	<h1><?php echo Mage::helper('storelocator')->__('Store Locator') ?></h1>
</div>

<?php
$lng = Mage::getStoreConfig('storelocator/storelocator/defaultlon');
$lat = Mage::getStoreConfig('storelocator/storelocator/defaultlat');
?>
<div id="store-locator-container">           
    <div id="form-container">
        <form id="user-location" method="post" action="#">
            <input type="hidden" name="location" value="<?php echo $this->getBaseUrl() . 'storelocator/storelocator/location/'; ?>" id="location">
            <input type="hidden" name="searchurl" value="<?php echo $this->getBaseUrl() . 'storelocator/storelocator/searchlocation/'; ?>" id="searchurl">
            <input type="hidden" name="infowindowdesc" value="<?php echo $this->getBaseUrl() . 'storelocator/storelocator/infowindowdescription/'; ?>" id="infowindowdesc">
            <input type="hidden" name="locationlist" value="<?php echo $this->getBaseUrl() . 'storelocator/storelocator/locationlistdescription/'; ?>" id="locationlist">
            <div id="form-input">
                <label for="address">Enter City OR State OR Phone OR Zip Code:</label>
                <input type="text" id="address" name="address" />
            </div>            
            <button id="submit" type="submit">Submit</button>
        </form>
    </div>

    <div id="map-container">	
        <div id="loc-list">
            <ul id="list"></ul>
        </div>
        <div id="map"></div>
    </div>
</div>

<script type="text/javascript">
    jQuery(function() {
        jQuery('#map-container').storeLocator({'slideMap' : false, 'defaultLoc': true, 'defaultLat': '<?php echo $lat; ?>', 'defaultLng' : '<?php echo $lng; ?>' });
    });
</script>